apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user 
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: rodrigogrohl/questcode-backend-user:0.1.2
        ports:
        - containerPort: 3020
        env:
        - name: NODE_ENV
          value: "staging"
        - name: MONGO_URI
          value: "mongodb+srv://edvangoulart:*Nivania103352@cluster0.mycqd4f.mongodb.net/test"
        - name: SECRET_OR_KEY
          value: "bootcamp18"