apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-scm
  labels:
    app: backend-scm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-scm
  template:
    metadata:
      labels:
        app: backend-scm
    spec:
      containers:
      - name: backend-scm
        image: rodrigogrohl/questcode-backend-scm:0.1.1
        ports:
        - containerPort: 3030
        env:
        - name: NODE_ENV
          value: "staging"
        - name: GITHUB_CLIENT_ID
          value: "a701f0b93863692e89b3"
        - name: GITHUB_CLIENT_SECRET
          value: "353d0a86c1a3a0143ab0bed726f6e7b542c216a7"
        - name: SECRET_OR_KEY
          value: "bootcamp18"  